version: '3.8'

services:
  git-server:
    build: .
    privileged: true
    ports:
      - "2222:22"
    volumes:
      - git-repo:/home/gituser/repo
      - nextjs-build:/app/build

  nginx:
    image: nginx:alpine
    privileged: true
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
    ports:
      - "80:80"
    volumes:
      - nextjs-build:/usr/share/nginx/html:ro
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - git-server

  ngrok:
    image: ngrok/ngrok:alpine
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTH_TOKEN}
    command: 'http nginx:80'
    depends_on:
      - nginx

volumes:
  git-repo:
  nextjs-build:
